language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py PYPY_VERSION=2.7-v7.3.1
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=py PYPY_VERSION=3.6-v7.3.1
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  - |
      if [[ ! -z "$PYPY_VERSION" ]]; then
        export PYPY_VERSION="pypy$PYPY_VERSION-linux64"
        wget "https://downloads.python.org/pypy/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/${PYPY_VERSION:0:5}" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
  - pip install -U tox twine wheel codecov

script: tox
after_success: codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapy
  password:
    secure: UnOnSBV254I8w44LXAwJgY3I1+Jnc+Oq7RlmYSfm6oq9qcWGrtXrPjFh6ZKV7RcrFDwFo4MtqI1E14X3DhPTmkTtDxsadbWESShE5a1SRYwQactRDW8QBQvwT8JEJy02GUAduoOznBQod7CegiccOygrAW1ULj+Fr72YVPN8tfI=
  on:
    tags: true
    all_branches: true
    repo: scrapy/queuelib
    condition: "$TOXENV == py27"

cache:
  directories:
    - $HOME/.cache/pip
